In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
# Import Polaris dataset downloaded...
eda_df = pd.read_csv(os.path.join("Potential_Data", "global_dataset_14_Apr_2020.csv"), header=1)
eda_df.head()

C:\Users\mrm\anaconda3\envs\GroupProjectEnv\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (6,55,57) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlDebtBondage,meansOfControlTakesEarnings,...,typeOfSexPrivateSexualServices,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown
NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
NaN,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1

In [8]:
# Feature engineering
# -99 is no data or NaN
eda_df["majorityStatusAtExploit"].replace({"-99": np.nan}, inplace=True)
eda_df.head(10)

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlDebtBondage,meansOfControlTakesEarnings,...,typeOfSexPrivateSexualServices,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown
NaN,2002.0,Case Management,Female,18--20,Adult,NaN,-99,CO,NaN,NaN,...,NaN,NaN,NaN,NaN,-99,0.0,0.0,0.0,0.0,1.0
NaN,2002.0,Case Management,Female,18--20,Adult,NaN,-99,CO,NaN,NaN,...,NaN,NaN,NaN,NaN,-99,0.0,0.0,0.0,0.0,1.0
NaN,2002.0,Case Management,Female,18--20,Adult,NaN,-99,CO,NaN,NaN,...,NaN,NaN,NaN,NaN,-99,0.0,0.0,0.0,0.0,1.0
NaN,2002.0,Case Management,Female,18--20,Adult,NaN,-99,CO,NaN,NaN,...,NaN,NaN,NaN,NaN,-99,0.0,0.0,0.0,0.0,1.0
NaN,2002.0,Case Management,Female,18--20,Adult,NaN,-99,CO,NaN,NaN,...,NaN,NaN,NaN,NaN,-99,0.0,0.0,0.0,0.0,1.0
NaN,2002.0,Case Management,Female,18--20,Adult,NaN,-99,CO,NaN,NaN,...,NaN,NaN,NaN,NaN,-99,0.0,0.0,0.0,0.0,1.0
NaN,2002.0,Case Management,Female,18--20,Adult,NaN,-99,CO,NaN,NaN,...,NaN,NaN,NaN,NaN,-99,0.0,0.0,0.0,0.0,1.0
NaN,2002.0,Case Management,Female,18--20,Adult,NaN,-99,CO,NaN,NaN,...,NaN,NaN,NaN,NaN,-99,0.0,0.0,0.0,0.0,1.0
NaN,2002.0,Case Management,Female,18--20,Adult,NaN,-99,CO,NaN,NaN,...,NaN,NaN,NaN,NaN,-99,0.0,0.0,0.0,0.0,1.0
NaN,2002.0,Case Management,Female,18--20,Adult,NaN,-99,CO,NaN,NaN,...,NaN,NaN,NaN,NaN,-99,0.0,0.0,0.0,0.0,1.0

In [9]:
eda_df["majorityStatusAtExploit"].isnull().sum()

39511

In [10]:
eda_df.shape

(48801, 63)