In [113]:
import os
import pandas as pd
import numpy as np

In [114]:
# Import Polaris dataset downloaded...
eda_df = pd.read_csv(os.path.join("Potential_Data", "global_dataset_14_Apr_2020.csv"), header=0)
eda_df.head()

C:\Users\mrm\anaconda3\envs\mlenv\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (54) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlDebtBondage,meansOfControlTakesEarnings,...,typeOfSexPrivateSexualServices,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown
0,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
1,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
2,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
3,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1
4,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,-99,0,0,0,0,1

In [115]:
eda_df.shape

(48801, 63)

## Feature Engineering

### Table 1: Data Category Groupings
| Grouped Category | Data Category | Data Code |
| ----- | ----- | ----- |
| Financial | meansOfControlDebtBondage  | 1 |
| Financial | meansOfControlTakesEarnings | 1 |
| Financial | meansOfControlRestrictsFinancialAccess | 1 |
| Threats | meansOfControlThreats | 2 |
| Threats | meansOfControlPsychologicalAbuse | 2 |
| Threats | meansOfControlFalsePromisesmeansOfControlUsesChildren | 2 |
| Threats | meansOfControlThreatOfLawEnforcement | 2 |
| Survival | meansOfControlRestrictsMedicalCare | 3 |
| Survival | meansOfControlWithholdsNecessities | 3 |
| Survival | meansOfControlWithholdsDocuments | 3 |
| Physical | meansOfControlPhysicalAbuse | 4 |
| Physical | meansOfControlSexualAbuse | 4 |
| Physical | meansOfControlRestrictsMovement | 4 |
| Other | meansOfControlNotSpecified | 5 |
| Other | meansOfControlPsychoactiveSubstances | 5 |

*Placeholder text*

In [116]:
# Create a sub-set of our larger DataFrame for experimenting
# eda_subset_df = eda_df.iloc[:5000]
# eda_subset_df.shape

In [117]:
control_means_list = []
for row in eda_df.iterrows():
# for row in eda_subset_df.iterrows():
    # Categorize by arbitrary grouping of 'Financial'
    if str(row[1]["meansOfControlDebtBondage"]) == "1" or str(row[1]["meansOfControlTakesEarnings"]) == "1" or str(row[1]["meansOfControlRestrictsFinancialAccess"]) == "1":
        control_means_list.append(1)
    # Categorize by arbitrary grouping of 'Threats'
    elif str(row[1]["meansOfControlThreats"]) == "1" or str(row[1]["meansOfControlPsychologicalAbuse"]) == "1" or str(row[1]["meansOfControlFalsePromises"]) == "1" or str(row[1]["meansOfControlUsesChildren"]) == "1" or str(row[1]["meansOfControlThreatOfLawEnforcement"]) == "1":
        control_means_list.append(2)
    # Categorize by arbitrary grouping of 'Survival'
    elif str(row[1]["meansOfControlRestrictsMedicalCare"]) == "1" or str(row[1]["meansOfControlWithholdsNecessities"]) == "1" or str(row[1]["meansOfControlWithholdsDocuments"]) == "1":
        control_means_list.append(3)
    # Categorize by arbitrary grouping of 'Physical'
    elif str(row[1]["meansOfControlPhysicalAbuse"]) == "1" or str(row[1]["meansOfControlSexualAbuse"]) == "1" or str(row[1]["meansOfControlRestrictsMovement"]) == "1":
        control_means_list.append(4)
    # Categorize by arbitrary grouping of 'Other'
    elif str(row[1]["meansOfControlNotSpecified"]) == "1" or str(row[1]["meansOfControlPsychoactiveSubstances"]) == "1":
        control_means_list.append(5)
    # Insert null value if none of the criteria above are met...
    else:
        # print("None")
        control_means_list.append(np.nan)

In [118]:
# eda_subset_df["control_category"] = control_means_list
# eda_subset_df["control_category"].value_counts()

# Add a column with our arbitrary category groupings back to the main DataFrame
eda_df["control_category"] = control_means_list
eda_df["control_category"].value_counts()

5.0    27129
2.0     4384
1.0     3250
4.0     1684
3.0      220
Name: control_category, dtype: int64

In [119]:
# Duplicate DataFrame and drop columns that we no longer need...
categorized_eda_df = eda_df
categorized_eda_df.drop(["meansOfControlDebtBondage", "meansOfControlTakesEarnings", "meansOfControlRestrictsFinancialAccess"], axis=1, inplace=True)
categorized_eda_df.drop(["meansOfControlThreats", "meansOfControlPsychologicalAbuse", "meansOfControlFalsePromises", "meansOfControlUsesChildren"], axis=1, inplace=True)
categorized_eda_df.drop(["meansOfControlRestrictsMedicalCare", "meansOfControlWithholdsNecessities", "meansOfControlWithholdsDocuments"], axis=1, inplace=True)
categorized_eda_df.drop(["meansOfControlPhysicalAbuse", "meansOfControlSexualAbuse", "meansOfControlRestrictsMovement"], axis=1, inplace=True)
categorized_eda_df.drop(["meansOfControlNotSpecified", "meansOfControlPsychoactiveSubstances"], axis=1, inplace=True)
categorized_eda_df.head()

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlExcessiveWorkingHours,meansOfControlThreatOfLawEnforcement,...,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown,control_category
0,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,0,0,0,0,1,5.0
1,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,0,0,0,0,1,5.0
2,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,0,0,0,0,1,5.0
3,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,0,0,0,0,1,5.0
4,2002,Case Management,Female,18--20,Adult,-99,-99,CO,-99,-99,...,-99,-99,-99,-99,0,0,0,0,1,5.0