In [1]:
import os
import pandas as pd

In [2]:
# Import World Bank poverty data
# https://data.worldbank.org/indicator/SI.POV.NAHC?view=map&year_high_desc=true

poverty_df = pd.read_csv("API_SI.POV.NAHC_DS2_en_csv_v2_2917413.csv")
poverty_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,...,38.3,NaN,NaN,NaN,NaN,54.5,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.3,NaN,NaN

In [3]:
# Drop unnecessary columns
poverty_df.drop(["Indicator Name",
            "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", 
            "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", 
            "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989",
            "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", 
            "2000", "2001", "2019", "2020"
            ], axis=1, inplace=True)
poverty_df.head()

,Country Name,Country Code,Indicator Code,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,33.7,NaN,NaN,NaN,38.3,NaN,NaN,NaN,NaN,54.5,NaN,NaN
3,Africa Western and Central,AFW,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,SI.POV.NAHC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.3

In [4]:
poverty_df = poverty_df[['Country Code', 'Indicator Code','Country Name', '2002', '2003', '2004', '2005', '2006', '2007',
                        '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018']]
poverty_df.head(20)

,Country Code,Indicator Code,Country Name,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,ABW,SI.POV.NAHC,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFE,SI.POV.NAHC,Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,SI.POV.NAHC,Afghanistan,NaN,NaN,NaN,NaN,NaN,33.7,NaN,NaN,NaN,38.3,NaN,NaN,NaN,NaN,54.5,NaN,NaN
3,AFW,SI.POV.NAHC,Africa Western and Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AGO,SI.POV.NAHC,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.3
5,ALB,SI.POV.NAHC,Albania,25.4,NaN,NaN,18.5,NaN,NaN,12.4,NaN,NaN,NaN,14.3,NaN,NaN,NaN,NaN,NaN,NaN
6,AND,SI.POV.NAHC,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ARB,SI.POV.NAHC,Arab World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ARE,SI.POV.NAHC,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,ARG,SI.POV.NAHC,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.3,25.7,32.0
10,ARM,SI.POV.NAHC,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,ASM,SI.POV.NAHC,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,ATG,SI.POV.NAHC,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,AUS,SI.POV.NAHC,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,AUT,SI.POV.NAHC,Austria,13.2,13.0,12.6,12.6,12.0,15.2,14.5,14.7,14.5,14.4,14.4,14.1,13.9,14.1,14.4,14.3,13.3
15,AZE,SI.POV.NAHC,Azerbaijan,NaN,NaN,NaN,NaN,NaN,15.8,13.2,10.9,9.1,7.6,6.0,NaN,NaN,NaN,NaN,NaN,NaN
16,BDI,SI.POV.NAHC,Burundi,NaN,NaN,NaN,NaN,67.1,NaN,NaN,NaN,NaN,NaN,NaN,64.9,NaN,NaN,NaN,NaN,NaN
17,BEL,SI.POV.NAHC,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.8
18,BEN,SI.POV.NAHC,Benin,NaN,NaN,NaN,NaN,37.5,33.0,NaN,NaN,35.2,36.2,NaN,NaN,NaN,40.1,NaN,NaN,NaN
19,BFA,SI.POV.NAHC,Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.4

In [6]:
# Save DF to CSV
poverty_df.to_csv('WorldBank_Poverty.csv', index = False)